const DESCRIPTIONS = {
  'affine.pro': 'The universal editor that lets you work, play, present or create just about anything.',
  'agenticapi.com': '- [![Agentic API: White paper and Implementation Strategy](https://agenticapi.com/wp-content/uploads/2025/05/agentic4.png)](https://agenticapi.com/agentic-api/)',
  'agentmail.to': 'The email inbox API for AI agents',
  'alterhq.com': 'Alter: The seamless AI that supercharges your Mac. Skip the chat, execute instant actions across all apps. 10x your productivity with complete privacy control.',
  'altrina.com': 'Altrina (altrina.com) automates SOPs and workflows with AI-powered agents. Built by ex-Google and NVIDIA engineers for teams that need reliable, scalable automation.',
  'apten.ai': 'AI agents that text & call like a human to convert leads. Customize AI conversation flows to guide leads down personalized experiences. Never forget to follow up.',
  'assemblyai.com': 'With AssemblyAI\'s industry-leading Speech AI models, transcribe speech to text and extract insights from your voice data.',
  'asteroid.ai': 'Transform your back-office operations with Asteroid\'s browser agents. Automate insurance quoting, healthcare data entry, and complex workflows without coding. HIPAA compliant, enterprise-ready.',
  'athina.ai': '![Hero Circle One](https://cdn.prod.website-files.com/670cb23343dfaffd7368be46/6716259337044b07a55d281e_Ellipse%20379.svg)![Hero Circle One](https://cdn.prod.website-files.com/670cb23343dfaffd7368be46',
  'axiom.ai': 'Build browser bots quickly, without code. Automate website actions and repetitive tasks using just your browser, on any website or web app.',
  'bolna.ai': 'Scale customer support, sales, recruitment with Bolna Voice Agents. Inbound and outbound calls in vernacular Indian languages like English, Hindi, Hinglish.',
  'botcity.dev': 'Enterprise governance for Python+AI at scale: monitor local executions, orchestrate automations with control, and generate insights and KPIs for security and compliance.',
  'browse.ai': 'Easily scrape web data, monitor webpage changes, and turn websites into APIs with Browse AI.',
  'canary.tools': 'Most companies discover they’ve been breached way too late. Thinkst Canary fixes this: just 2 minutes of setup; nearly 0 false positives, no ongoing overhead, and you can detect attackers long before',
  'castari.com': 'The deployment platform for Claude agents. Build, deploy, and scale AI agents with one command.',
  'ccapi.ai': 'One OpenAI-compatible API for 100+ AI models. Text, image, audio & video with smart routing and auto failover. Pay-per-use, no subscription.',
  'cerebrium.ai': 'A serverless cloud infrastructure platform that makes it easy to build and deploy AI applications scalably and performantly. Run serverless GPUs with low cold starts, choose from over 10 GPU types, ru',
  'codebuff.com': 'Code faster with AI using Codebuff. Edit your codebase and run terminal commands via natural language instruction.',
  'codrify.online': 'Codrify.ai New Pay as you go Version now free until Feb 8th !! Powered by Deepseek V3., Talk with Bolt, an AI assistant from StackBlitz, Talk with Bolt, an AI assistant from StackBlitz',
  'compyle.ai': 'Stop wasting time on 20-minute builds that do the wrong thing. Compyle keeps you in the driver\'s seat—planning together first, then asking when anything\'s unclear.',
  'confident-ai.com': 'The AI quality layer for engineers, QA teams, and product leaders to build reliable AI.',
  'cont3xt.dev': 'Give Cursor, Copilot, and Claude your coding patterns. Stop wasting time fixing AI suggestions that violate your standards. Free for individuals.',
  'contextual.ai': 'Replace DIY complexity with the context engineering platform built for accuracy. Ship production-grade AI that is secure, scalable, and specialized.',
  'cubic.dev': 'cubic is an Al code review platform that helps teams like Cal.com and n8n catch bugs and merge pull requests faster 28% faster.',
  'dagworks.io': 'Dagworks, Inc.',
  'daily.co': 'Daily is the team behind Pipecat. Ultra low latency, open source SDKs, and enterprise reliability since 2016.',
  'datasaur.ai': 'Datasaur builds secure, private LLMs for regulated enterprises. Deploy custom AI workflows behind your firewall to ensure full data privacy and compliance.',
  'decisional.com': 'Automate complex operational workflows with AI agents that read, code, and use spreadsheets. 10X easier than traditional automation tools.',
  'elkapi.com': 'Free For A Limited Time! Register Now',
  'ellipsis.dev': 'Automated code reviews and bug fixes. Software engineers are more productive with Ellipsis, a developer tool that catches bugs, answers questions, and generates working, tested code.',
  'embedder.com': 'Generate production-ready C++ & Rust firmware from datasheets. Automate register mapping, timing diagrams, and HIL/SIL verification with hardware-aware AI.',
  'everydev.ai': 'Discover, review, and discuss AI tools. Join the community where builders share insights, rate tools, and connect around AI development.',
  'exa.ai': 'Real-time AI search engine with a powerful web search API, web crawling API, SERP API, and deep research tools. Search and extract structured content from websites and live data.',
  'fiber.ai': 'Get 100% deliverable contacts (with phones and emails) powered by AI, or your money back.',
  'firebender.com': 'The Most Powerful Coding Agent for Android Studio',
  'firecrawl.dev': 'The web crawling, scraping, and search API for AI. Built for scale. Firecrawl delivers the entire internet to AI agents and builders. Clean, structured, and ready to reason with.',
  'floot.com': 'Build serious apps without coding in minutes., With Testimonial, in minutes, you can collect and display video testimonials and other types of testimonials from your customers with no need for a devel',
  'flowiseai.com': 'Open source generative AI development platform for building AI agents, LLM orchestration, and more',
  'getzep.com': 'Agents fail without the right context. Getting it right is hard. We fixed it. Goes beyond agent memory with unified context graph, Graph RAG, and automated context assembly. Works with any framework.',
  'gigamind.dev': 'No more getting stuck as your project grows. AI that actually understands your codebase. Compatible with VSCode, Cursor, Claude, Codex, and more.',
  'giselles.ai': 'Supercharge your productivity with Giselle. Build custom AI applications visually, no coding required. Automate research, reports, creative tasks, and more by integrating top AI models and your data.',
  'greptile.com': 'AI Code Reviews that understand your entire codebase. Automate PR reviews, catch bugs faster, improve code quality with AI-driven analysis. Try Greptile free!',
  'helicone.ai': 'Routing and monitoring for reliable AI apps - the LLMOps platform behind the fastest-growing AI companies.',
  'heyapi.dev': '🌀 OpenAPI to TypeScript codegen. Production-ready SDKs, Zod schemas, TanStack Query hooks, and 20+ plugins. Used by Vercel, OpenCode, and PayPal.',
  'heylua.ai': 'Build, deploy, and scale enterprise-grade AI agents. Ship your first agent without touching infrastructure.',
  'humanloop.com': 'Humanloop is joining Anthropic to accelerate the adoption of AI, safely.',
  'hyperbrowser.ai': 'Cloud browsers for AI agents & Apps',
  'hyperspell.com': 'The memory and context layer for your AI agent. Designed with your safety, privacy, and control in mind.',
  'inconvo.com': 'Inconvo is a developer platform for building reliable data agents that safely query production databases with semantic models, permissions, and structured outputs.',
  'inspectorio.com': 'We allow Brands, Retailers, Vendors and Factories to improve Quality, Compliance and Delivery operations with tangible insights and data-driven collaboration.',
  'kernel.ai': 'Resolve entity identities, build hierarchies, increase firmographic accuracy, and turn your CRM into a trusted foundation for territory design.',
  'kinde.com': 'Kinde is the all-in-one developer platform for authentication, access management and billing - secure and monetize your SaaS from day one.',
  'klavis.ai': 'Klavis AI is the MCP infrastructure layer for AI. We provide sandboxed environments for training LLMs on tool use, and enterprise-grade integrations for AI apps with auth built in.',
  'laminar.sh': 'Open-source platform to trace, evaluate, and improve AI agents. Debug LLM calls, track tool use, and run evaluations on your AI applications.',
  'langfuse.com': 'Traces, evals, prompt management and metrics to debug and improve your LLM application. Integrates with Langchain, OpenAI, LlamaIndex, LiteLLM, and more.',
  'maven.com': 'Live courses with real-world experts in AI, Product, Leadership, Design, Data & engineering, Marketing & sales, and Business & finance.',
  'mem0.ai': 'Mem0 enables AI apps to continuously learn from past user interactions, enhancing their intelligence and personalization.',
  'middleware.io': 'Middleware offers full-stack observability with real-time monitoring and diagnostics, helping teams detect issues at scale while keeping data secure.',
  'mike.gg': 'Read thoughts by Michael Tromba on entrepreneurship, startup building, and engineering. Learn from someone who has built 30+ apps reaching 27M+ users.',
  'mychamberai.app': 'AI-powered automation platform for Chambers of Commerce and local businesses. Automate bookings, follow-ups, and payments.',
  'myclone.is': 'MyClone - AI Experts Platform',
  'openmemory.dev': 'With OpenMemory, add persistent, project-aware memory to Cursor, Windsurf, and VS Code agents. Store preferences, patterns, and context that get retrieved automatically.',
  'orthogonal.com': 'The building blocks your agent needs.',
  'oversteer.dev': 'Fast, Repeatable, and Reliable Browser Agent',
  'pacy.dev': 'Use your browser to develop apps with your favorite AI agents. Seamlessly integrates with Claude Code, Cursor, and more.',
  'parea.ai': 'The experimentation and human annotation platform for AI teams.',
  'parse.bot': 'Describe what you need in plain English. Parse reverse-engineers any website and gives you a live REST API endpoint in minutes. No browser, no code, no maintenance.',
  'promptdc.com': 'Better prompts = Better coding results. Vibe coding prompting. One-click prompt rewriting for AI web platforms (Lovable, Bolt, Replit) and local editors (Cursor, VS Code, Windsurf).',
  'querypie.com': 'QueryPie AI is here to help you achieve successful AI transformation in your life and business. Delivering affordable enterprise AI, integrating with your existing infrastructure, and supporting your',
  'recall.ai': 'Recall.ai provides an API to get recordings, transcripts and metadata from video conferencing platforms like Zoom, Google Meet Microsoft Teams, and more. Get this data with our Meeting Bot API, Deskto',
  'reducto.ai': 'Reducto provides high-quality document ingestion for AI teams by accurately parsing complex documents like PDFs, Excel spreadsheets, and PowerPoint slides. Get started for free.',
  'retellai.com': 'Build, test, deploy, and monitor production-ready AI voice agents at scale with ease, boosting efficiency and performance across your operations.',
  'reworkd.ai': 'End to End Web Scraping',
  'riveterhq.com': 'Riveter replaces your entire scraper infrastructure with a single API.',
  'roark.ai': 'Catch the \'uh-oh\' moments before your customers do. Roark is the safety net that lets your team ship voice AI with confidence. Monitor calls, run simulations, turn failures into tests.',
  'runcopycat.com': 'CopyCat deploys custom AI workforces for enterprise — browser automation, email workflows, document processing, and cross-system orchestration. Live in days, not months.',
  'sigmamind.ai': 'Build and deploy production-grade voice AI agents using a single prompt, real-time tool orchestration, and low-latency voice infrastructure.',
  'skillsafe.ai': 'SkillSafe is the secured skill registry for AI coding tools. Scan, save, share, and verify skills with dual-side cryptographic verification.',
  'superagent.sh': 'We attack your production system to surface data leaks, harmful outputs, and unwanted actions. Fix them before your users encounter them.',
  'sweep.dev': 'The fastest AI copilot for JetBrains. Write code 10x faster with intelligent autocomplete and an AI agent.',
  'tambo.co': 'Build agents that speak your UI',
  'tess.im': 'Access ChatGPT, Claude, Gemini, and 250+ AI models in one professional platform. Deploy across unlimited team members and organizations. Start free today.',
  'tessl.ai': 'Tessl helps teams build AI-native software by giving coding agents structured, versioned context. Ship AI-powered systems that hold up in real codebases.',
  'tessl.io': 'Tessl helps teams build AI-native software by giving coding agents structured, versioned context. Ship AI-powered systems that hold up in real codebases.',
  'theneo.io': 'AI-native docs & portals: API, SDK & product docs with AI search, automatic changelogs, interactive reference, and branding. Import OpenAPI/Markdown and publish in seconds., AI-native docs & portals:',
  'toolkit-cli.com': 'Infrastructure for autonomous development in git-based forges. 18 months of agent-built infrastructure. Your competitors are using this in confidential production.',
  'traceloop.com': 'Traceloop turns evals and monitors into a continuous feedback loop - so every release gets better',
  'trykeet.com': 'Keet automates the manual data extraction and validation process for implementation managers. Allowing enterprises to onboard new customers in minutes.',
  'tryterra.co': 'Health API that enables you to integrate with wearables, such as Garmin, Fitbit, Apple, Google, Polar, Eight Sleep, Oura and Others through a single source',
  'trytruffle.ai': 'Powerful Automation. Automate complex workflows and processes with AI agents that learn and adapt to your business needs.',
  'unsiloed.ai': '![YCombinator](https://www.unsiloed.ai/ycomb.png)Backed by YCombinator',
  'usetusk.ai': 'Best AI testing tool for API testing, unit testing, and integration testing. Prevent regressions and boost code coverage with high-quality automated tests.,',
  'vellum.ai': 'Create powerful AI agents by chatting with AI. With Vellum, just describe what you want and your agent starts working. What once took a team of engineers now takes a single conversation.',
  'veryfi.com': 'OCR API for data extraction, mobile SDK for document capture, and toolkits to liberate trapped data in your unstructured documents like invoices, bills, purchase orders, checks (cheques) and receipts',
  'vybe.build': 'Enterprise-ready custom apps. Built by AI. Powered by your data. Ready in seconds.',
  'waydev.co': '✅ Waydev’s developer productivity insights deliver unparalleled insights into engineering productivity using AI Agents, DORA Metrics, Developer Experience (DX) analysis, and the SPACE Framework. Our D',
  'withwoz.com': 'Build real mobile apps you can actually launch in the App Store, confidently share with customers, and maintain with ease. Woz is the first platform that applies AI with expert human oversight to buil',
  'x.ai': 'xAI builds Grok, a free AI chatbot with voice chat, image and video generation, real-time search, and advanced reasoning. Try Grok at grok.com. xAI is an AI company with the mission of advancing scien',
  'zerogpt.org': 'ZeroGPT is an AI detection platform for identifying AI-generated text and images. Trusted by 200K+ educators and professionals. 98.5% accuracy.',
};
// 99 descriptions loaded
