"""Shared fixtures for cv-rank tests."""

from __future__ import annotations

import copy
import sys
from pathlib import Path
from typing import Any

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cv_rank.config import DEFAULT_CONFIG


@pytest.fixture()
def sample_people() -> list[dict[str, Any]]:
    """Return a list of 6 realistic person dicts as produced by load_csv."""
    return [
        {
            "name": "Alice Chen",
            "first_name": "Alice",
            "last_name": "Chen",
            "email": "alice@example.com",
            "linkedin_url": "https://linkedin.com/in/alicechen",
            "github_url": "https://github.com/alicechen",
            "company": "Anthropic",
            "role": "Senior ML Engineer",
            "location": "San Francisco",
            "x_handle": "@alice_ml",
            "self_description": "ML engineer building safe AI systems",
            "ai_project": "LLM alignment toolkit",
            "years_experience": "8",
            "is_founder": "false",
            "is_big_tech": "true",
            "is_student": "false",
            "top_school": "true",
            "education_level": "Masters",
            "employment_category": "employed",
            "looking_for_job": "false",
            "linkedin_headline": "ML @ Anthropic",
            "linkedin_followers": "5200",
            "linkedin_connections": "1800",
            "github_bio": "Building safe AI",
            "github_stars": "340",
            "github_followers": "120",
            "github_repos": "45",
            "github_commits_year": "890",
            "publications": "3",
            "certifications": "",
            "notable_achievements": "NeurIPS best paper 2024",
            "hackathon_submissions": "2",
            "total_cv_events": "4",
            "_raw_csv": {"Name": "Alice Chen", "Email": "alice@example.com"},
        },
        {
            "name": "Bob Martinez",
            "first_name": "Bob",
            "last_name": "Martinez",
            "email": "bob@startup.io",
            "linkedin_url": "https://linkedin.com/in/bobmartinez",
            "github_url": "https://github.com/bobm",
            "company": "AI Startup Inc",
            "role": "CTO & Co-Founder",
            "location": "New York",
            "x_handle": "@bobm_ai",
            "self_description": "Serial entrepreneur, AI-first companies",
            "ai_project": "Real-time fraud detection with LLMs",
            "years_experience": "12",
            "is_founder": "true",
            "is_big_tech": "false",
            "is_student": "false",
            "top_school": "false",
            "education_level": "Bachelors",
            "employment_category": "founder",
            "looking_for_job": "false",
            "linkedin_headline": "CTO @ AI Startup Inc",
            "linkedin_followers": "8900",
            "linkedin_connections": "3400",
            "github_bio": "Building cool stuff",
            "github_stars": "1200",
            "github_followers": "450",
            "github_repos": "78",
            "github_commits_year": "1560",
            "publications": "",
            "certifications": "AWS Solutions Architect",
            "notable_achievements": "YC W23, $5M seed",
            "hackathon_submissions": "5",
            "total_cv_events": "7",
            "_raw_csv": {"Name": "Bob Martinez", "Email": "bob@startup.io"},
        },
        {
            "name": "Carol Okafor",
            "first_name": "Carol",
            "last_name": "Okafor",
            "email": "carol@university.edu",
            "linkedin_url": "https://linkedin.com/in/carolokafor",
            "github_url": "",
            "company": "MIT",
            "role": "PhD Candidate",
            "location": "Cambridge, MA",
            "x_handle": "",
            "self_description": "Researching multimodal AI safety",
            "ai_project": "Multimodal jailbreak detection",
            "years_experience": "3",
            "is_founder": "false",
            "is_big_tech": "false",
            "is_student": "true",
            "top_school": "true",
            "education_level": "PhD",
            "employment_category": "student",
            "looking_for_job": "true",
            "linkedin_headline": "PhD @ MIT CSAIL",
            "linkedin_followers": "1200",
            "linkedin_connections": "800",
            "github_bio": "",
            "github_stars": "",
            "github_followers": "",
            "github_repos": "",
            "github_commits_year": "",
            "publications": "8",
            "certifications": "",
            "notable_achievements": "ICML 2024 oral; Google PhD Fellow",
            "hackathon_submissions": "1",
            "total_cv_events": "2",
            "_raw_csv": {"Name": "Carol Okafor", "Email": "carol@university.edu"},
        },
        {
            "name": "David Kim",
            "first_name": "David",
            "last_name": "Kim",
            "email": "david.kim@bigcorp.com",
            "linkedin_url": "https://linkedin.com/in/davidkim",
            "github_url": "https://github.com/dkim",
            "company": "Google DeepMind",
            "role": "Staff Research Scientist",
            "location": "London",
            "x_handle": "@dkim_research",
            "self_description": "Scaling laws and efficient training",
            "ai_project": "Distributed training framework",
            "years_experience": "15",
            "is_founder": "false",
            "is_big_tech": "true",
            "is_student": "false",
            "top_school": "true",
            "education_level": "PhD",
            "employment_category": "employed",
            "looking_for_job": "false",
            "linkedin_headline": "Staff Research Scientist @ DeepMind",
            "linkedin_followers": "15000",
            "linkedin_connections": "5000",
            "github_bio": "Research scientist at DeepMind",
            "github_stars": "2800",
            "github_followers": "890",
            "github_repos": "32",
            "github_commits_year": "430",
            "publications": "25",
            "certifications": "",
            "notable_achievements": "Gemini core team; 50+ citations",
            "hackathon_submissions": "0",
            "total_cv_events": "1",
            "_raw_csv": {"Name": "David Kim", "Email": "david.kim@bigcorp.com"},
        },
        {
            "name": "Elena Volkov",
            "first_name": "Elena",
            "last_name": "Volkov",
            "email": "elena@devtools.co",
            "linkedin_url": "",
            "github_url": "https://github.com/elenavolkov",
            "company": "DevTools Co",
            "role": "Founding Engineer",
            "location": "Berlin",
            "x_handle": "@elena_dev",
            "self_description": "Open source enthusiast, Rust and Python",
            "ai_project": "AI code review bot",
            "years_experience": "6",
            "is_founder": "true",
            "is_big_tech": "false",
            "is_student": "false",
            "top_school": "false",
            "education_level": "Bachelors",
            "employment_category": "founder",
            "looking_for_job": "false",
            "linkedin_headline": "",
            "linkedin_followers": "",
            "linkedin_connections": "",
            "github_bio": "Building dev tools with AI",
            "github_stars": "5400",
            "github_followers": "2100",
            "github_repos": "95",
            "github_commits_year": "2300",
            "publications": "",
            "certifications": "",
            "notable_achievements": "Created popular OSS linter; 10k+ GitHub stars total",
            "hackathon_submissions": "8",
            "total_cv_events": "12",
            "_raw_csv": {"Name": "Elena Volkov", "Email": "elena@devtools.co"},
        },
        {
            "name": "Fatima Al-Rashid",
            "first_name": "Fatima",
            "last_name": "Al-Rashid",
            "email": "fatima@healthcare.ai",
            "linkedin_url": "https://linkedin.com/in/fatimaalrashid",
            "github_url": "https://github.com/fatimar",
            "company": "HealthcareAI",
            "role": "VP of Engineering",
            "location": "Dubai",
            "x_handle": "",
            "self_description": "AI for healthcare, 10+ years shipping ML products",
            "ai_project": "Medical imaging diagnostic assistant",
            "years_experience": "10",
            "is_founder": "false",
            "is_big_tech": "false",
            "is_student": "false",
            "top_school": "true",
            "education_level": "Masters",
            "employment_category": "employed",
            "looking_for_job": "false",
            "linkedin_headline": "VP Eng @ HealthcareAI",
            "linkedin_followers": "3200",
            "linkedin_connections": "2100",
            "github_bio": "Healthcare AI",
            "github_stars": "180",
            "github_followers": "55",
            "github_repos": "18",
            "github_commits_year": "340",
            "publications": "6",
            "certifications": "Board Certified in Clinical Informatics",
            "notable_achievements": "FDA-approved AI diagnostic tool",
            "hackathon_submissions": "3",
            "total_cv_events": "5",
            "_raw_csv": {"Name": "Fatima Al-Rashid", "Email": "fatima@healthcare.ai"},
        },
    ]


@pytest.fixture()
def sample_config() -> dict[str, Any]:
    """Return a valid config dict based on DEFAULT_CONFIG with event.name set."""
    cfg = copy.deepcopy(DEFAULT_CONFIG)
    cfg["event"]["name"] = "Test AI Summit 2026"
    cfg["event"]["type"] = "community_meetup"
    cfg["event"]["target_accepts"] = 3
    cfg["models"]["scoring"] = "gpt-4o"
    cfg["enrichment"]["supabase"]["url"] = "https://test.supabase.co"
    cfg["enrichment"]["supabase"]["key"] = "test-key"
    return cfg


@pytest.fixture()
def tmp_run_dir(tmp_path):
    """Return a temporary run directory."""
    run_dir = tmp_path / "run_001"
    run_dir.mkdir(parents=True, exist_ok=True)
    return run_dir
